name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: 1.12.0.1530
          bb: 1.12.200
      - name: Run Babashka tests
        run: bb test-bb
      - name: Call run-tests-in-file-tree from bb
        run: bb test-bb-run-tests-in-file-tree
      - name: Run Clojure tests
        run: bb test-clj
